language: python
python:
- "3.5"
cache: pip
install:
- pip install coverage
- pip install flake8
- pip install codecov
script:
- flake8 .
- nosetests -sv --with-coverage --cover-package=aptos
after_success:
- codecov
